//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoOp
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRA
    {
        public int ID { get; set; }
        public string TYTUL { get; set; }
        public Nullable<int> PLATFORMA { get; set; }
        public Nullable<int> GATUNEK { get; set; }
        public Nullable<int> INTERNET { get; set; }
        public Nullable<int> LAN { get; set; }
        public Nullable<int> SPLIT { get; set; }
        public string OBRAZEK { get; set; }
        public string OPIS { get; set; }
    
        public virtual GATUNEK GATUNEK1 { get; set; }
        public virtual PLATFORMA PLATFORMA1 { get; set; }
    }
}
