//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoOp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CoOpEntities : DbContext
    {
        public CoOpEntities()
            : base("name=CoOpEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GATUNEK> GATUNEK { get; set; }
        public virtual DbSet<GRA> GRA { get; set; }
        public virtual DbSet<PLATFORMA> PLATFORMA { get; set; }
    
        public virtual ObjectResult<filterInternetGames_Result> filterInternetGames(Nullable<int> platforma, Nullable<int> ilu)
        {
            var platformaParameter = platforma.HasValue ?
                new ObjectParameter("Platforma", platforma) :
                new ObjectParameter("Platforma", typeof(int));
    
            var iluParameter = ilu.HasValue ?
                new ObjectParameter("Ilu", ilu) :
                new ObjectParameter("Ilu", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<filterInternetGames_Result>("filterInternetGames", platformaParameter, iluParameter);
        }
    
        public virtual ObjectResult<filterLANGames_Result> filterLANGames(Nullable<int> platforma, Nullable<int> ilu)
        {
            var platformaParameter = platforma.HasValue ?
                new ObjectParameter("Platforma", platforma) :
                new ObjectParameter("Platforma", typeof(int));
    
            var iluParameter = ilu.HasValue ?
                new ObjectParameter("Ilu", ilu) :
                new ObjectParameter("Ilu", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<filterLANGames_Result>("filterLANGames", platformaParameter, iluParameter);
        }
    
        public virtual ObjectResult<filterSPLITGames_Result> filterSPLITGames(Nullable<int> platforma, Nullable<int> ilu)
        {
            var platformaParameter = platforma.HasValue ?
                new ObjectParameter("Platforma", platforma) :
                new ObjectParameter("Platforma", typeof(int));
    
            var iluParameter = ilu.HasValue ?
                new ObjectParameter("Ilu", ilu) :
                new ObjectParameter("Ilu", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<filterSPLITGames_Result>("filterSPLITGames", platformaParameter, iluParameter);
        }
    
        public virtual ObjectResult<getPCGames_Result> getPCGames(Nullable<int> ilu)
        {
            var iluParameter = ilu.HasValue ?
                new ObjectParameter("Ilu", ilu) :
                new ObjectParameter("Ilu", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getPCGames_Result>("getPCGames", iluParameter);
        }
    
        public virtual ObjectResult<getPSGames_Result> getPSGames(Nullable<int> platforma, Nullable<int> ilu)
        {
            var platformaParameter = platforma.HasValue ?
                new ObjectParameter("Platforma", platforma) :
                new ObjectParameter("Platforma", typeof(int));
    
            var iluParameter = ilu.HasValue ?
                new ObjectParameter("Ilu", ilu) :
                new ObjectParameter("Ilu", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getPSGames_Result>("getPSGames", platformaParameter, iluParameter);
        }
    
        public virtual ObjectResult<getXboxGames_Result> getXboxGames(Nullable<int> platforma, Nullable<int> ilu)
        {
            var platformaParameter = platforma.HasValue ?
                new ObjectParameter("Platforma", platforma) :
                new ObjectParameter("Platforma", typeof(int));
    
            var iluParameter = ilu.HasValue ?
                new ObjectParameter("Ilu", ilu) :
                new ObjectParameter("Ilu", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getXboxGames_Result>("getXboxGames", platformaParameter, iluParameter);
        }
    
        public virtual int removeGame(string tytul)
        {
            var tytulParameter = tytul != null ?
                new ObjectParameter("Tytul", tytul) :
                new ObjectParameter("Tytul", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("removeGame", tytulParameter);
        }
    }
}
